#!/usr/bin/env bash

# You can execute me through Glide by doing the following:
# - Execute `glide slow`
# - ???
# - Profit

pushd $GOPATH/src/github.com/aerokite/go-avro-convert

glide up -v
glide vc --only-code --no-tests --no-test-imports

popd
